Repository cardinal-dev/Cardinal, pull requests merged in 2019-06, with the labels that each got.

#42 app: added flask routes for ap statistics
  README.md
  add_new_ap.php
  app/main.py
  app/templates/add-ap.html
  app/templates/dashboard.html
  app/templates/total-ap-groups.html
  app/templates/total-aps.html
  app/templates/total-clients.html
  app/templates/total-ssids.html
  dashboard.php
  graph_ap_clients.php
  graph_ap_groups.php
  graph_total_aps.php
  graph_total_ssids.php
Labels: cleanup, enhancement, structure change

#43 app: improved mysql operations within main.py
  app/main.py
Labels: cleanup, enhancement

#44 app: updated flask routes for Cardinal operations
  app/main.py
  app/templates/add-ap-group.html
  app/templates/add-ap.html
  app/templates/dashboard.html
  app/templates/delete-ap-group.html
  app/templates/delete-ap.html
  app/templates/network-tools.html
  delete_ap_group.php
  delete_aps.php
  functions/delete_ap_group_calc.php
  functions/delete_aps_calc.php
  network_tools.php
Labels: cleanup, enhancement

#45 app: added routes for Network Toolkit
  app/main.py
  app/templates/network-tools-output.html
  app/templates/network-tools.html
  network_tools_curl.php
  network_tools_dig.php
  network_tools_nmap.php
  network_tools_ping.php
  network_tools_tracert.php
  network_tools_whois.php
Labels: cleanup, enhancement, structure change

#46 app: updated AP dashboard operations to Flask
  .travis.yml
  app/main.py
  app/templates/choose-ap-dashboard.html
  app/templates/dashboard.html
  app/templates/manage-ap-dashboard.html
  app/templates/total-ap-bandwidth.html
  app/templates/total-ap-clients.html
  bin/install.sh
  graph_ap_bandwidth.php
  graph_per_ap_clients.php
  manage_ap_wizard.php
Labels: cleanup, enhancement, structure change

#47 app: added Flask routes for AP group dashboard
  app/main.py
  app/templates/choose-ap-group-dashboard.html
  app/templates/config-ap-ip.html
  app/templates/dashboard.html
  app/templates/manage-ap-dashboard.html
  app/templates/manage-ap-group-dashboard.html
  configure_ap_ip.php
  manage_ap_group_wizard.php
Labels: cleanup, enhancement, structure change

#48 bin: updated core Cardinal definitions
  bin/build.sh
  bin/install.sh
  bin/scout.py
Labels: bug, cleanup, enhancement

#49 cardinal: updated install.sh script to reflect werkzeug hash check
  app/main.py
  bin/install.sh
Labels: bug, enhancement

#50 Travis CI: Remove Python 3.4 because it is EOL and add 3.7
  .travis.yml
Labels: build ops

#51 Cardinal: Changed license headers to reflect Cardinal Contributors
  LICENSE
  README.md
  app/main.py
  bin/build.sh
  bin/install.sh
  bin/scout.py
Labels: license

#52 app: added delimiters to SQL statements
  app/main.py
Labels: bug

#53 cardinal: fixed dashboard mysql query bug
  .travis.yml
  app/main.py
  bin/install.sh
  requirements.txt
  sql/cardinal.sql
Labels: bug, enhancement

#54 .travis.yml: added python sql connection test
  .travis.yml
  ci/cardinal.ini
  ci/cardinalmysql.ini
  ci/sqltest.py
Labels: build ops

#55 cardinal: PHP to Python Updates
  .travis.yml
  app/main.py
  app/templates/config-ap-ip.html
  app/templates/config-ap-name.html
  bin/scout.py
  configure_ap_name.php
  functions/configure_ap_ip_calc.php
  functions/configure_ap_name_calc.php
  includes/cardinalconfig.php
Labels: build ops, cleanup, enhancement
